<a href="https://colab.research.google.com/github/NivasMaturi/ML-Lab/blob/main/program2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#2.Study of python basic libraries
import math

num = 9
angle_degrees = 45

print("Square Root:", math.sqrt(num))
print("Factorial:", math.factorial(5))
print("Logarithm base 10:", math.log10(100))
print("Sine of 45 degrees:", math.sin(math.radians(angle_degrees)))
print("Value of Pi:", math.pi)


Square Root: 3.0
Factorial: 120
Logarithm base 10: 2.0
Sine of 45 degrees: 0.7071067811865475
Value of Pi: 3.141592653589793


In [2]:
import math

# Example numbers
num1 = 4.3
num2 = 9.7
num3 = -2.8
num4 = 5.0

# Applying ceil function
print("Ceil of", num1, "is:", math.ceil(num1))  # Output: 5
print("Ceil of", num2, "is:", math.ceil(num2))  # Output: 10
print("Ceil of", num3, "is:", math.ceil(num3))  # Output: -2
print("Ceil of", num4, "is:", math.ceil(num4))  # Output: 5 (unchanged)


Ceil of 4.3 is: 5
Ceil of 9.7 is: 10
Ceil of -2.8 is: -2
Ceil of 5.0 is: 5


In [3]:
#numpy basics
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"







<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [4]:
import numpy as np

# Creating a 3D array (2 layers, 3 rows, 4 columns)
arr_3d = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],

    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])

print("3D Array:\n", arr_3d)
print(arr_3d[0, 1, 2])  # Access element in 1st layer, 2nd row, 3rd column → Output: 7
print(arr_3d[1, 2, 3])  # Access element in 2nd layer, 3rd row, 4th column → Output: 24


3D Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
7
24


In [5]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.23643909 0.83472351]
 [0.96266185 0.77488758]]
